In [1]:
import glob, os, json
import time
import pickle
import solver
import traceback

In [14]:
tspLibPath = "../data/tsplib/"

# Load TSP instances
tspLibInstances = []
tspInstanceNames = []
for file in glob.glob(tspLibPath + "*.tsp"):
    try:
        tsp = solver.loadTSPLib(file)
        tspLibInstances.append(tsp)
        tspInstanceNames.append(os.path.basename(file))
    except:
        traceback.print_exc()

In [15]:
generatedPath = "../data/generated/"

# Load TSP instances
generatedInstances = []
generatedInstanceNames = []
for file in glob.glob(generatedPath + "*.pytsp"):
    try:
        tspFile = open(file, "rb")
        tsp = pickle.load(tspFile)
        generatedInstances.append(tsp)
        generatedInstanceNames.append(os.path.basename(file))
        tspFile.close()
    except:
        traceback.print_exc()

In [16]:
allInstances = tspLibInstances + generatedInstances
allInstanceNames = tspInstanceNames + generatedInstanceNames

In [2]:
def measureFeature(name, deterministic, tsp, data, features, featureFunction):
    start = time.time()
    value = featureFunction(tsp, data)
    end = time.time()
    
    storedValue = value
    if type(storedValue).__module__=='numpy': # if value is numpy.*: > to python list
        storedValue = storedValue.tolist()
    
    if deterministic:
        features[name] = storedValue
    else:
        valueName = name + "Values"
        if valueName not in features:
            features[valueName] = []
            
        features[valueName].append(storedValue)
        
    timeName = name + "Times"
    
    if timeName not in features:
        features[timeName] = []
    
    features[timeName].append(end - start)
    
    return value

In [3]:
def stripNumpyDict(dictionary):
    for key in dictionary:
        value = dictionary[key]
        if isinstance(value, dict):
            stripNumpyDict(value)
        if isinstance(value, list):
            dictionary[key] = stripNumpyArray(value)
        elif type(value).__module__=='numpy': # if value is numpy.*: > to python list
            dictionary[key] = value.item()
            
def stripNumpyArray(array):
    newArray = []
    for item in array:
        if isinstance(item, list):
            newArray.append(stripNumpyArray(array))
        elif type(item).__module__=='numpy': # if value is numpy.*: > to python list
            newArray.append(item.item())
        else:
            newArray.append(item)
            
    return newArray

In [8]:
from network.features import *
from network.simpleFeatures import *
from network.complexFeatures import *
from network.heuristicFeatures import *
import json

nLowestEdgeCosts = 10

def generateSimpleFeatures(tsp, features, n):
    simple = {}
    for i in range(n):
        print("Starting Simple Features %d" % (i + 1))
        measureFeature("numberVertices", True, tsp, None, simple, lambda tsp, _: numberVertices(tsp))
        
        vertexCosts = measureFeature("vertexCostPrep", True, tsp, None, simple, lambda tsp, _: buildVertexCosts(tsp))
        data = {"vertexCosts": vertexCosts}
        measureFeature("lowestVertexCost", True, tsp, data, simple, lambda _, data: lowestVertexCost(data["vertexCosts"]))
        measureFeature("highestVertexCost", True, tsp, data, simple, lambda _, data: highestVertexCost(data["vertexCosts"]))
        measureFeature("averageVertexCost", True, tsp, data, simple, lambda _, data: averageVertexCost(data["vertexCosts"]))
        measureFeature("standardDeviationVertexCost", True, tsp, data, simple, lambda _, data: standardDeviationVertexCost(data["vertexCosts"]))
        measureFeature("medianVertexCost", True, tsp, data, simple, lambda _, data: medianVertexCost(data["vertexCosts"]))
        
        measureFeature("sumCostNearestNeighbor", True, tsp, None, simple, lambda tsp, _: sumCostNearestNeighbor(tsp))
        measureFeature("numberEdges", True, tsp, None, simple, lambda tsp, _: numberEdges(tsp))
        measureFeature("lowestEdgeCost", True, tsp, None, simple, lambda tsp, _: lowestEdgeCost(tsp))
        measureFeature("highestEdgeCost", True, tsp, None, simple, lambda tsp, _: highestEdgeCost(tsp))
        measureFeature("averageEdgeCost", True, tsp, None, simple, lambda tsp, _: averageEdgeCost(tsp))
        measureFeature("standardDeviationEdgeCost", True, tsp, None, simple, lambda tsp, _: standardDeviationEdgeCost(tsp))
        measureFeature("medianEdgeCost", True, tsp, None, simple, lambda tsp, _: medianEdgeCost(tsp))
        measureFeature("sumNLowestEdgeCost", True, tsp, None, simple, lambda tsp, _: sumNLowestEdgeCost(tsp, nLowestEdgeCosts))
        
        print("Ending Simple Features %d" % (i + 1))
        
    features["simpleFeatures"] = simple
    
def generateComplexFeatures(tsp, features, n):
    complexFeatures = {}
    for i in range(n):
        print("Starting Complex Features %d" % (i + 1))
        measureFeature("averageShortestPathGeodesicDistance", True, tsp, None, complexFeatures, lambda tsp, _: averageShortestPathGeodesicDistance(tsp))
        measureFeature("averageGeodesicDistance", True, tsp, None, complexFeatures, lambda tsp, _: averageGeodesicDistance(tsp))
        
        globalEfficiencyValue = measureFeature("globalEfficiency", True, tsp, None, complexFeatures, lambda tsp, _: globalEfficiency(tsp))
        data = {"globalEfficiency": globalEfficiencyValue}
        measureFeature("harmonicMeanGeodesicDistance", True, tsp, None, complexFeatures, lambda tsp, _: harmonicMeanGeodesicDistance(tsp))
        
        measureFeature("networkVulnerability", True, tsp, data, complexFeatures, lambda tsp, data: networkVulnerability(tsp, data["globalEfficiency"]))
        
        measureFeature("clusteringCoefficientTransitivity", True, tsp, None, complexFeatures, lambda tsp, _: clusteringCoefficientTransitivity(tsp))
        measureFeature("alternateClusteringCoefficient", True, tsp, None, complexFeatures, lambda tsp, _: alternateClusteringCoefficient(tsp))
        
        connectedEdgeCountsValue = measureFeature("connectedEdgeCountsPrep", True, tsp, None, complexFeatures, lambda tsp, _: connectedEdgeCounts(tsp))
        data = {"connectedEdgeCounts": connectedEdgeCountsValue}
        measureFeature("weightedClusteringCoefficient", True, tsp, data, complexFeatures, lambda tsp, data: weightedClusteringCoefficient(tsp, data["connectedEdgeCounts"]))
        measureFeature("networkCyclicCoefficient", True, tsp, data, complexFeatures, lambda tsp, data: networkCyclicCoefficient(tsp, data["connectedEdgeCounts"]))
        measureFeature("maxVertexDegree", True, tsp, data, complexFeatures, lambda _, data: maxVertexDegree(data["connectedEdgeCounts"]))
        measureFeature("edgeDegreeCorrelation", True, tsp, data, complexFeatures, lambda tsp, data: edgeDegreeCorrelation(tsp, data["connectedEdgeCounts"]))
        
        measureFeature("entropyDegreeDistribution", True, tsp, None, complexFeatures, lambda tsp, _: entropyDegreeDistribution(tsp))
        measureFeature("targetEntropy", True, tsp, None, complexFeatures, lambda tsp, _: targetEntropy(tsp))
        measureFeature("vertexParticipationCoefficient", True, tsp, None, complexFeatures, lambda tsp, _: vertexParticipationCoefficient(tsp))
        measureFeature("edgeReciprocity", True, tsp, None, complexFeatures, lambda tsp, _: edgeReciprocity(tsp))
        measureFeature("adjacencyCorrelationCoefficient", True, tsp, None, complexFeatures, lambda tsp, _: adjacencyCorrelationCoefficient(tsp))
        
        print("Ending Complex Features %d" % (i + 1))
        
    features["complexFeatures"] = complexFeatures
        
def generateFeatures(tsp, filename, n):
    features = {}
    
    generateSimpleFeatures(tsp, features, n)
    generateComplexFeatures(tsp, features, n)
    
    stripNumpyDict(features)
    
    with open(filename, "w") as file:
        json.dump(features, file)


In [9]:
allInstanceNames

NameError: name 'allInstanceNames' is not defined

In [10]:
tsp = solver.loadTSPLib("/Users/adam/Documents/Rose Repos/Thesis/data/tsplib/ch130.tsp")

In [11]:
features = {}
generateFeatures(tsp, "../data/features/tsplib/ch130.json", 1)

Starting Simple Features 1
Ending Simple Features 1
Starting Complex Features 1
Ending Complex Features 1
{'simpleFeatures': {'numberVertices': 130, 'numberVerticesTimes': [5.245208740234375e-06], 'vertexCostPrep': [297.1577448509223, 266.17981371280666, 315.4475930641637, 274.1246260189174, 396.5070435727815, 439.03581169132195, 405.46094038533573, 309.66018775024145, 436.87359751528714, 402.66905875628026, 397.7275567912588, 325.4129442177554, 406.1660775532017, 398.40462250416715, 288.771362080862, 341.214916949064, 264.3228252150921, 294.40435717619545, 281.21714896385714, 274.56897235704383, 310.3501606208629, 315.5578154595597, 334.84070909593936, 287.39255892901565, 385.1707389743273, 386.7438460668381, 273.53948429291444, 411.86308021120925, 300.30261603647506, 361.85513710450243, 265.98807227008564, 396.54427319207304, 317.24059326876295, 270.78667652553014, 264.1484610664759, 398.67684992634804, 312.6543917296114, 296.1150258448843, 298.59452646975814, 320.3387717317367, 299.

In [8]:
features

{}

In [6]:
tsp.getSize()

130

In [7]:
buildVertexCosts(tsp)

0


IndexError: too many indices for array

In [18]:
import numpy
test = numpy.array(tsp.getSize())

In [13]:
test[0] = 1

IndexError: too many indices for array

In [14]:
test.shape

()

In [26]:
features = {"test": [numpy.int_(5)]}

stripNumpyDict(features)

with open("test.json", "w") as file:
    json.dump(features, file)

In [14]:
sortedCosts = numpy.sort(tsp.costs[numpy.nonzero(tsp.costs)], axis=None)

In [15]:
sortedCosts

array([  6.60180990e-01,   6.60180990e-01,   2.23623041e+00, ...,
         9.38517244e+02,   9.38842335e+02,   9.38842335e+02])

In [16]:
tsp.costs

array([[   0.        ,  119.09645956,  169.64633859, ...,   89.76011102,
         166.56933504,   81.6422314 ],
       [ 119.09645956,    0.        ,  139.19177174, ...,  175.81408796,
         270.55303015,   57.19837622],
       [ 169.64633859,  139.19177174,    0.        , ...,  146.43591543,
         332.82245704,  105.86886018],
       ..., 
       [  89.76011102,  175.81408796,  146.43591543, ...,    0.        ,
         207.5325414 ,  119.84887942],
       [ 166.56933504,  270.55303015,  332.82245704, ...,  207.5325414 ,
           0.        ,  246.87507296],
       [  81.6422314 ,   57.19837622,  105.86886018, ...,  119.84887942,
         246.87507296,    0.        ]])

In [17]:
tsp.costs[numpy.nonzero(tsp.costs)]

array([ 119.09645956,  169.64633859,  248.29638486, ...,  207.21526864,
        119.84887942,  246.87507296])